name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: false
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: false
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  GOOGLE_GENERATIVE_AI_API_KEY:
    description: "Google generative AI API key."
    required: false
  GOOGLE_GENERATIVE_AI_MODEL:
    description: "Google generative AI model."
    required: false
    default: "gemini-1.5-pro"
  AI_VENDOR:
    description: "AI vendor to use for code review."
    required: true
    default: "google"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
